COMPILER ?= gcc

CC=$(CROSS_COMPILE)$(COMPILER)
CPP=$(CROSS_COMPILE)cpp
OBJCOPY=$(CROSS_COMPILE)objcopy

WORKDIR ?= .

# --- Compiler and Linker Flags ---
#  Use -fno-PIC to avoid .got relocation table which will contain absoulte
#  addresses
CFLAGS += -O0 -fno-PIC -fno-common -ffreestanding -ffunction-sections -fdata-sections
CFLAGS += -march=rv64imafdcv_zifencei_zicsr -mabi=lp64d
ASFLAGS = $(CFLAGS)
LDFLAGS += -nostdlib -static -Wl,--gc-sections

INCLUDE := include
HEADERS := $(wildcard $(INCLUDE)/*.h $(WORKDIR)/*.h)
CPPFLAGS := -I$(WORKDIR) -I$(INCLUDE)

# Add include paths
ifneq ("$(wildcard $(WORKDIR)/platform.h)","")
  CPPFLAGS += -DHAVE_PLATFORM_H
endif

# --- Source Files ---
CSOURCES := $(wildcard init/*.c $(WORKDIR)/*.c)
SSOURCES := $(wildcard init/*.S $(WORKDIR)/*.S)
SRCS := $(CSOURCES) $(SSOURCES)
OBJS := $(SRCS:.c=.o)
OBJS := $(OBJS:.S=.o)

# Collect build targets (platforms, examples, tests)
TARGETS := $(wildcard */)
TARGETS := $(patsubst %/,%,$(TARGETS))
# Remove init directory and include from the list
TARGETS := $(filter-out init include,$(TARGETS))

# Collect all linker scripts in WORKDIR, only if is not the root directory '.'
WORKDIR_LDS :=
ifneq ($(WORKDIR),.)
  WORKDIR_LDS := $(wildcard $(WORKDIR)/*.ld)
endif

# --- Set Target Name ---
# Target name matches folder/project name
ifneq ($(WORKDIR),.)
  # For platform folders: use folder name (e.g., handoff)
  TARGET_NAME := $(WORKDIR)
else
  # For root: hart-init
  TARGET_NAME := hart-init
endif

# --- Targets ---
ELF := $(WORKDIR)/$(TARGET_NAME).elf
BIN := $(WORKDIR)/$(TARGET_NAME).bin

# --- Default Target ---
root: $(BIN)

all: root $(TARGETS)


# --- Phony targets ---
.PHONY: root all clean clean-workdir clean-all clean-% $(TARGETS)


# --- Build Rules ---

# Compile C files
%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Compile Assembly files
%.o: %.S $(HEADERS)
	$(CC) $(ASFLAGS) $(CPPFLAGS) -c $< -o $@

# Linker script generated by preprocessing init .ld file
GENERATED_LD = $(WORKDIR)/generated.ld

# Generate the preprocessed linker script
$(GENERATED_LD): init/init.ld $(HEADERS)
	$(CC) $(CFLAGS) $(CPPFLAGS) -E -P -x c $< -o $@

# Build the ELF
# $(GENERATED_LD) must come first; additional linker scripts from $(WORKDIR) follow
$(ELF): $(OBJS) $(WORKDIR_LDS) $(GENERATED_LD)
	$(CC) $(LDFLAGS) $(CFLAGS) $(CPPFLAGS) \
	    -T $(GENERATED_LD) $(addprefix -T ,$(WORKDIR_LDS)) $(OBJS) -o $@

# Create the final binary from the ELF file
$(BIN): $(ELF)
	$(OBJCOPY) -O binary $< $@


# --- Directory-specific Targets ---

# Build for any discovered target (e.g., 'make handoff')
$(TARGETS):
	$(MAKE) WORKDIR=$@

# Root-only clean
clean:
	rm -f init/*.o *.o $(TARGET_NAME).elf $(TARGET_NAME).bin $(WORKDIR)/generated.ld

# Clean everything by recursively calling clean targets
clean-all: clean
	@for dir in $(TARGETS); do \
	    $(MAKE) WORKDIR=$$dir clean-workdir; \
	done

# Clean a specific folder
clean-%:
	$(MAKE) WORKDIR=$* clean-workdir

clean-workdir:
	rm -f init/*.o $(WORKDIR)/*.o $(WORKDIR)/$(TARGET_NAME).elf $(WORKDIR)/$(TARGET_NAME).bin $(WORKDIR)/generated.ld
